[[plugins]]
repo = 'elixir-editors/vim-elixir'
on_ft = ['elixir', 'eelixir']

[[plugins]]
repo = 'slashmili/alchemist.vim'
on_ft = ['elixir', 'eelixir']

[[plugins]]
repo = 'c-brenn/phoenix.vim'
on_ft = ['elixir', 'eelixir']

[[plugins]]
repo = 'mhinz/vim-mix-format'
on_ft = ['elixir', 'eelixir']
hook_add = '''"vim
  let g:mix_format_on_save = 1
'''
