[[plugins]]
repo = 'tbastos/vim-lua'
on_ft = 'lua'

[[plugins]]
repo = 'xolox/vim-misc'
on_ft = 'lua'

[[plugins]]
repo = 'xolox/vim-lua-ftplugin'
on_ft = 'lua'
hook_source = '''"vim
  let g:lua_complete_omni = 1
  let g:lua_check_syntax = 0
  let g:lua_complete_dynamic = 0
  let g:lua_define_completion_mappings = 0

  let g:deoplete#custom#source('omni', 'functions', {
  \ 'lua': 'xolox#lua#omnifunc'
  \ })
'''
