[[plugins]]
repo = 'tpope/vim-bundler'

[[plugins]]
repo = 'sunaku/vim-ruby-minitest'

[[plugins]]
repo = 'nelstrom/vim-textobj-rubyblock'

[[plugins]]
repo = 'vim-ruby/vim-ruby'
hook_add = '''"vim
  let g:ruby_indent_assignment_style = 'variable'
  let g:ruby_indent_block_style = 'do'
'''
