[[plugins]]
repo = 'tpope/vim-bundler'

[[plugins]]
repo = 'tpope/vim-cucumber'

[[plugins]]
repo = 'sunaku/vim-ruby-minitest'

[[plugins]]
repo = 'ecomba/vim-ruby-refactoring'

[[plugins]]
repo = 'nelstrom/vim-textobj-rubyblock'

[[plugins]]
repo = 'vim-ruby/vim-ruby'
hook_add = '''"vim
  let g:rubycomplete_buffer_loading = 1
  let g:rubycomplete_rails = 1
'''
