[[plugins]]
repo = 'mhartington/nvim-typescript'
on_ft = 'typescript'

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'typescript'

[[plugins]]
repo = 'HerringtonDarkholme/yats.vim'
on_ft = 'typescript'
